# Site settings - reference http://ben.balter.com/2015/02/20/jekyll-collections/
title: Testing title
email: ckiriaze@gmail.com
description: A blog about my favorite web conferences.

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
# baseurl: /path/to/blog
baseurl: /juice # for github pages, uncomment this line, and recomment for local dev env

twitter_username: kiriaze
paginate: 3
# Pagination path › Important for blog page in /blog/ to work
paginate_path: blog/page:num

# Build settings
markdown: kramdown
permalink: /blog/:categories/:title

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'assets']
# keep jekyll from removing compiled css dir
keep_files: ['assets']

# Src/Dest are also outlined in config.js
source: ./src
destination: ./dist

relative_permalinks: false
highlighter: true # syntax highlighting

navigation:
 - title: Home
   url: /index.html
 - title: Grid
   url: /grid
 - title: Type
   url: /type
 - title: Blog
   url: /blog
 - title: My Collection
   url: /my-collection

collections:
  my-collection: # name of collection
    output: true
    permalink: /my-collection/:path/
    # That way, _my-collection/item.md is outputted as my-collection/item/index.html when the site is built and would be accessable as example.com/my-collection/item/. The other advantage, is, because the data is now structured and machine readable (rather than in plain text), you could also use the jsonify filter to output that same information as an API for use elsewhere.

# Default settings
defaults:
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: default category
      comments: true
      author: "your_author_name"
      layout: "post"
  -
    scope:
      path: "" 				# an empty string here means all files in the project
      type: "my-collection"
    values:
      layout: "my-collection"
