# Site settings
title: Testing title
email: ckiriaze@gmail.com
description: A blog about my favorite web conferences.

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
# baseurl: /path/to/blog
url: "http://domain.com" # the base hostname & protocol for your site

twitter_username: kiriaze
paginate: 3

# Build settings
markdown: kramdown
permalink: /blog/:category/:title

exclude: ['node_modules', 'gulpfile.js', 'package.json', 'assets']
# keep jekyll from removing compiled css dir
keep_files: ['assets']

# Src/Dest are also outlined in config.js
source: ./src
destination: ./dist

relative_permalinks: false
highlighter: true # syntax highlighting
